spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    initial-size: 3
    max-total: 5
    max-idle: 3
    min-idle: 1

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  health:
    status:
      order: DOWN, UP
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

eureka:
  instance:
    instance-id: coupon-api
    hostname: eureka-server
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://admin:1234@eureka-server:8761/eureka

api:
  gateway:
    host: buzz-book.store
    port: 8080

nhncloud:
  keymanager:
    appkey: 2SxwmBzUfnqJaA2A
    mysql:
      url: 0e5015e36f91453d806dbd77ba595347
      username: 0f85ac52219545d382eab76db989e848
      password: 54e01f8caa504a6ca5e69d30e66bf348
