spring:
  application:
    name: coupon

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/be6_aa_dev?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: be6_aa
    password: 6@H(77fpCZDiC6!!
    type: org.apache.commons.dbcp2.BasicDataSource
    initial-size: 5
    max-total: 10
    max-idle: 5
    min-idle: 3

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true

